apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aeroinbox-secret-provider
  namespace: aeroinbox
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "7fa7bff6-f2d8-4246-8302-f57ec184b4bc"
    keyvaultName: "kv-aeroinbox-prod"
    tenantId: "ea3249a3-251c-42d6-96a8-15bb78609c9f"
    objects: |
      array:
        - |
          objectName: service-bus-connection-string
          objectType: secret
  secretObjects:
    - secretName: meeting-service-secrets
      type: Opaque
      data:
        - objectName: service-bus-connection-string
          key: service-bus-connection-string
