apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: "7fa7bff6-f2d8-4246-8302-f57ec184b4bc"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meeting-service-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: "7fa7bff6-f2d8-4246-8302-f57ec184b4bc"
  labels:
    azure.workload.identity/use: "true"
