apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: "6bce6129-2921-4302-ab1f-7e3b069218d0"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meeting-service-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: "6bce6129-2921-4302-ab1f-7e3b069218d0"
  labels:
    azure.workload.identity/use: "true"
