apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rule-engine-netpol
  namespace: aeroinbox
spec:
  podSelector:
    matchLabels:
      app: rule-engine-service
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-service
    ports:
    - protocol: TCP
      port: 8000
