apiVersion: v1
kind: Service
metadata:
  name: ai-service-svc
  namespace: aeroinbox
  labels:
    app: ai-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: ai-service
